-- ============================================================
-- E-Commerce Sales ETL Pipeline
-- SQL Analysis Queries
-- ============================================================

USE DATABASE ECOMMERCE_DB;
USE SCHEMA SALES;


-- ============================================================
-- 1. TOTAL REVENUE
-- Calculates the total revenue generated from all order items
-- ============================================================

SELECT
    ROUND(SUM(revenue), 2) AS total_revenue
FROM ORDER_ITEMS;


-- ============================================================
-- 2. REVENUE BY PRODUCT
-- Shows quantity sold and revenue generated by each product
-- ============================================================

SELECT
    p.product_id,
    p.product_name,
    SUM(oi.quantity) AS total_quantity_sold,
    ROUND(SUM(oi.revenue), 2) AS total_revenue
FROM ORDER_ITEMS oi
JOIN PRODUCTS p
    ON oi.product_id = p.product_id
GROUP BY
    p.product_id,
    p.product_name
ORDER BY total_revenue DESC;


-- ============================================================
-- 3. REVENUE BY PRODUCT CATEGORY
-- Shows sales performance for each product category
-- ============================================================

SELECT
    p.category,
    SUM(oi.quantity) AS total_quantity_sold,
    ROUND(SUM(oi.revenue), 2) AS total_revenue
FROM ORDER_ITEMS oi
JOIN PRODUCTS p
    ON oi.product_id = p.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;


-- ============================================================
-- 4. TOP CUSTOMERS BY REVENUE
-- Shows customers ranked by their total spending
-- ============================================================

SELECT
    c.customer_id,
    c.customer_name,
    COUNT(DISTINCT o.order_id) AS total_orders,
    SUM(oi.quantity) AS total_items_purchased,
    ROUND(SUM(oi.revenue), 2) AS total_revenue
FROM CUSTOMERS c
JOIN ORDERS o
    ON c.customer_id = o.customer_id
JOIN ORDER_ITEMS oi
    ON o.order_id = oi.order_id
GROUP BY
    c.customer_id,
    c.customer_name
ORDER BY total_revenue DESC;


-- ============================================================
-- 5. MONTHLY REVENUE
-- Shows order count and revenue for each month
-- ============================================================

SELECT
    DATE_TRUNC('MONTH', o.order_date) AS order_month,
    COUNT(DISTINCT o.order_id) AS total_orders,
    ROUND(SUM(oi.revenue), 2) AS total_revenue
FROM ORDERS o
JOIN ORDER_ITEMS oi
    ON o.order_id = oi.order_id
GROUP BY order_month
ORDER BY order_month;


-- ============================================================
-- 6. REVENUE BY PAYMENT METHOD
-- Shows order count and revenue for each payment method
-- ============================================================

SELECT
    o.payment_method,
    COUNT(DISTINCT o.order_id) AS total_orders,
    ROUND(SUM(oi.revenue), 2) AS total_revenue
FROM ORDERS o
JOIN ORDER_ITEMS oi
    ON o.order_id = oi.order_id
GROUP BY o.payment_method
ORDER BY total_revenue DESC;


-- ============================================================
-- 7. ORDER STATUS ANALYSIS
-- Shows the number of orders and revenue for each status
-- ============================================================

SELECT
    o.order_status,
    COUNT(DISTINCT o.order_id) AS total_orders,
    ROUND(SUM(oi.revenue), 2) AS total_revenue
FROM ORDERS o
JOIN ORDER_ITEMS oi
    ON o.order_id = oi.order_id
GROUP BY o.order_status
ORDER BY total_orders DESC;